spring.application.name=hartmann

spring.datasource.url=jdbc:sqlserver://${DB_SERVER};databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

hartmann.images.source=${IMAGES_SOURCE:ftp}
hartmann.images.local.base-path=${IMAGES_LOCAL_BASE_PATH:./images}
hartmann.images.ftp.base-url=${FTP_BASE_URL:}
hartmann.images.ftp.host=${FTP_HOST:}
hartmann.images.ftp.port=${FTP_PORT:21}
hartmann.images.ftp.username=${FTP_USERNAME:}
hartmann.images.ftp.password=${FTP_PASSWORD:}
hartmann.images.ftp.base-path=${FTP_BASE_PATH:/}
hartmann.images.ftp.passive-mode=${FTP_PASSIVE_MODE:true}
hartmann.images.ftp.connect-timeout-millis=${FTP_CONNECT_TIMEOUT_MILLIS:5000}
hartmann.images.ftp.data-timeout-millis=${FTP_DATA_TIMEOUT_MILLIS:10000}

spring.mail.host=${MAIL_HOST:smtp.office365.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:mail}
spring.mail.password=${MAIL_PASSWORD:pass}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.connectiontimeout=15000
#spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000
spring.mail.properties.mail.debug=true

spring.mail.default-encoding=UTF-8
